### ISSUE TITLE
render svg tag does not work

### ISSUE THREAD

**Issue by gutenye** [violentmonkey/vm-dom#1]
**The Problem**

```
render <svg viewBox="0 0 24 24">..</svg>
returns <svg viewbox="0 0 24 24">..</svg>   # the viewbox case is lowered
```

**The Cause**

svg is XML element, it's case-sensitive, unlike HTML element. see more [here](https://stackoverflow.com/a/28734954), that means we need to use `document.createElementNS('http://www.w3.org/2000/svg', 'svg');` to create svg element instead of `document.createElementNS('http://www.w3.org/1999/xhtml', 'svg');`, need to fix the code [here](https://github.com/violentmonkey/vm-dom/blob/9e51d59b9836cc8b75ad9f06e8d7fa57f2c8cf59/src/index.ts#L5)

**How to fix**

React is using [parentNamespace](https://github.com/facebook/react/blob/f50ff357cf45d5cbda8d5a99c247e33b0477e936/packages/react-dom/src/shared/DOMNamespaces.js#L33)

**Comment by gera2ld** [comment]
SVG is supported in `@violentmoney/vm-dom@2`, also based on parent namespace.
However the usage is changed, JSX needs to be wrapped with `VM.m`, for example:

```js
document.body.append(VM.m(<div>hello</div>));
document.body.append(VM.m(<svg viewBox="0 0 24 24">..</svg>));
```
