### ISSUE TITLE
VM.observe Options

### ISSUE THREAD

**Issue by influential-eliot** [violentmonkey/vm-dom#8]
Hi, sorry ... I may have missed it in the docs, but how does one set this to [watch for attribute changes](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/observe#attributes) (or other [options](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/observe#options))? I cannot seem to find anything about it anywhere.

Apologies if this is a dumb question ... and if it's currently unsupported, all good ... will try to remember how to get things done the old ways! 😅

**Comment by gera2ld** [comment]
Thanks for reaching out.
Actually you may check [the code](https://github.com/violentmonkey/vm-dom/blob/bf2c8abae1a6f5bca9cc4e192ded07840146e785/src/index.ts#L64-L71) directly. It's just a light wrapper for convenience.

There is a third parameter `options` merged into the defaults and passed to `observer.observe`:

```ts
VM.observe(node, callback, {
  // Override the defaults as needed
  childList: true,
  subtree: true,
  // your options here
});
```

**Comment by influential-eliot** [comment]
Aha, thanks, @gera2ld ... unfortunately that code is basically like trying to read Mandarin, for me. It's beautiful, and I respect its history, but I have next-to-no idea what's going on. 😅 

So, in order to use the options (_and I use jquery, because I am not clever enough for full JS_) ... would it look something like this?
```javascript
VM.observe(document.body, () => {
  childList: true,
  subtree: true,
  
  // Find the target node
  const $node = $('ATTRIBUTE_NODE_I_AM_MONITORING_FOR');

  if ($node.length) {
    $node.attr('contenteditable', 'true');

    // disconnect observer - This is disabled as if you disconnect you cannot enter more comments
    // return true;
  }
});
```

_I do not disconnect, because I want it to replace more than one occurrence of this and not just stop after the first._

For some odd reason this feels wrong. 😩

**Comment by gera2ld** [comment]
```js
VM.observe(document.body, () => {
  // Find the target node
  const $node = $('ATTRIBUTE_NODE_I_AM_MONITORING_FOR');

  if ($node.length) {
    $node.attr('contenteditable', 'true');

    // disconnect observer - This is disabled as if you disconnect you cannot enter more comments
    // return true;
  }
}, {
  childList: true,
  subtree: true,
  // any other options here
});
```

**Comment by influential-eliot** [comment]
Aha!

You're amazing, @gera2ld ! Thank you so much. ❤️ 🏆 

(_I'll see if I can find a way to suggest something like that is updated into the [observer docs](https://violentmonkey.github.io/guide/observing-dom/)!_)
